# Generated by Django 5.2.11 on 2026-02-23 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Accessories'), ('keys', 'Keys'), ('wallet', 'Wallet & IDs'), ('backpack', 'Backpack & Bags'), ('jewelry', 'Jewelry'), ('books', 'Books & Notes'), ('sports', 'Sports Equipment'), ('other', 'Other')], default='other', max_length=50)),
                ('location', models.CharField(help_text='Where was it lost/found?', max_length=200)),
                ('date_lost', models.DateField(help_text='Date item was lost or found')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('contact_email', models.EmailField(help_text='Email address people can reach you at', max_length=254)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found / Claimed')], default='lost', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
