# Generated by Django 6.0.3 on 2026-04-23 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='location',
        ),
        migrations.AddField(
            model_name='lostitem',
            name='found_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='storage_status',
            field=models.CharField(choices=[('REPORTER', 'I have it with me'), ('SITE', 'I left it where I found it'), ('DROPOFF', 'I left it at a drop-off location')], default='SITE', max_length=10),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Claimed')], default='lost', max_length=20),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='drop_off_location',
            field=models.ForeignKey(blank=True, help_text='Where is this item or where was it left?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='our_site.location'),
        ),
    ]
